### ISSUE TITLE
Dashboard did not even show

### ISSUE THREAD

**Issue by yuanshi4** [fairlearn/fairlearn#484] opened 2020-06-16 17:18 UTC
#### Describe the issue linked to the documentation

when I was trying to access the dashboard, the user interactive dashboard did not show up, I only see [out]:<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f0206c42cc0>

**Comment by romanlutz** [comment] 2020-06-16 17:54
Please run 
```python
from fairlearn import show_versions
show_versions()
```
and paste the output here. That should provide us with some information on your context.

It's likely that you need to reload the browser page with the jupyter notebook (assuming you're running one) and rerun the cell with the dashboard. This is an issue a few people have faced.

Tagging @rihorn2 for awareness.

**Comment by yuanshi4** [comment] 2020-06-17 18:20
![version](https://user-images.githubusercontent.com/60263695/84934672-4871e800-b09d-11ea-9b07-7507644b83ce.jpg)

**Comment by yuanshi4** [comment] 2020-06-17 18:21
I tried multiple attempts, using show( ) or display( ), the dashboard is still not showing up...Thank you for your help btw!

**Comment by yuanshi4** [comment] 2020-06-17 18:22
I am working on Jupyter Notebook btw

**Comment by romanlutz** [comment] 2020-06-17 18:25
Did you try reloading the page before rerunning it?

Can you also tell us which version of Fairlearn you're using? `pip freeze` should tell you

**Comment by yuanshi4** [comment] 2020-06-17 18:26
Yes, I did, tried reloading multiple times, and even restart kernel and re-run everything.

**Comment by riedgar-ms** [comment] 2020-06-17 18:26
Which browser/OS is this?

**Comment by yuanshi4** [comment] 2020-06-17 18:27
Chrome on Windows
Fairlearn version is 0.4.6

**Comment by yuanshi4** [comment] 2020-06-17 18:34
And the jupyter notebook is on AWS environment (doubt if that matters)

**Comment by riedgar-ms** [comment] 2020-06-17 18:35
You mean that you have a windows VM in AWS, and you're RDPing to it, and running the notebook there?

**Comment by riedgar-ms** [comment] 2020-06-17 18:37
Also, what version of Jupyter? As @romanlutz  said, if you could attach your `pip freeze` it would be very helpful.

**Comment by riedgar-ms** [comment] 2020-06-17 18:46
I've just used the following requirements file:
```
scikit-learn==0.23.1
numpy==1.18.5
scipy==1.4.1
pandas==1.0.4
Cython==0.28.4
matplotlib==3.0.3
fairlearn==0.4.6
```
and then doing a regular install of jupyter (and shap). With that, I can load one of our sample notebooks, and load the dashboard in Chrome.

I'm slightly puzzled by one thing - your output from `show_versions()` above implies that you're running on a Linux box. On my laptop, I get:
```
System:
    python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
executable: c:\users\riedgar\appdata\local\continuum\miniconda3\envs\bug-testing\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
       pip: 20.1.1
setuptools: 47.3.0.post20200616
   sklearn: 0.23.1
     numpy: 1.18.5
     scipy: 1.4.1
    Cython: 0.28.4
    pandas: 1.0.4
matplotlib: 3.0.3
    tempeh: None
```

**Comment by yuanshi4** [comment] 2020-06-17 19:02
I'm using the AWS server so I think that's why they showed a Linux system?

jupyter == 1.0.0
jupyter-client ==5.2.3
jupyter-consele==5.2.0
jupyter-core==4.4.0
jupyterlab = = 0.32.1
jupyterlab-launcher==0.10.5

**Comment by yuanshi4** [comment] 2020-06-17 19:03
I have no idea what's the cause of this issue, I can view an interactive plot through ipywidget...

**Comment by riedgar-ms** [comment] 2020-06-17 19:22
I'm still confused as to where and how the notebook is running. It almost sounds as if you're using a browser on Windows with the kernel running on a Linux machine in AWS?

If so, are you able to run the notebook locally, on the Windows machine? Or run the whole stack (browser and all) on the Linux box?

**Comment by romanlutz** [comment] 2020-06-17 21:54
I've heard people say it doesn't work on jupyterlab if that's what you're using.

It sounds like you have a Windows machine with Chrome, but the notebook is running on a Linux VM. Has anyone tried running the dashboard in Linux?

**Comment by bricha2** [comment] 2020-06-26 18:07
I had a similar problem! I am on a Linux VM (on Google Cloud AI Platform) using Jupyter Lab and upon inspecting the webpage, I see some error messages saying 'Fairlearn-Widget semver range  ^0.1.1 is not registered as a widget module'. I will screen shot below for reference.
![Screen Shot 2020-06-26 at 2 05 47 PM](https://user-images.githubusercontent.com/13242069/85887771-6387da80-b7b6-11ea-99e6-c7d5326c7a03.png)

**Comment by riedgar-ms** [comment] 2020-06-26 19:18
Tag @rihorn2

**Comment by rihorn2** [comment] 2020-06-29 12:45
@bricha2 The current Fairlearn package does not support visualization in Jupyter Labs, only Jupyter notebook. This is an area we are actively working on addressing, and will update this thread when there is support in Labs. In the meantime, could you check if the visualizations are appearing in a notebook tab?

**Comment by bricha2** [comment] 2020-06-29 19:26
Yeah, so when I move to Jupyter Notebook (within the GCS), I am getting the same errors in the console of the page. I am going to try it locally and get back to you.

**Comment by bricha2** [comment] 2020-06-29 20:56
And this is to confirm it did work locally.

**Comment by sagu94271** [comment] 2020-07-10 12:26
It is even not appearing in the Google Colab.

**Comment by sagu94271** [comment] 2020-07-10 12:44
Visualizations are not appearing in azure notebooks(which is jupyter notebook) : <fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f90943abc88>

**Comment by rihorn2** [comment] 2020-07-10 14:02
@sagu94271  The fairlearn dashboard does render in a jupyter notebook running on an azure compute instance
![image](https://user-images.githubusercontent.com/29712031/87162579-1dda1000-c294-11ea-83c7-f7b5cd2febf4.png)
As stated above, the dashboard relies on IPython Widget currently, which limits it to jupyter notebooks. The other environments mentioned that are not jupyter notebook-based will not work with the current communication layer. We are working on moving to a local flask service, but setting up the correct forwarding and auth for other cloud environments will require work per environment.

**Comment by sagu94271** [comment] 2020-07-10 15:24
Thanks for the update @rihorn2 .After refresh It is indeed working with Local jupyter notebook

**Comment by torfjelde** [comment] 2020-07-20 15:47
Hey! This looks like an awesome package and so I wanted to give it a try, buuut ran into the same issues as described above. 

This happens on a local instance of jupyter notebooks:
![image](https://user-images.githubusercontent.com/11074788/87957720-ea2b9100-cab0-11ea-8d13-9260135dcf82.png)

And for info:
![image](https://user-images.githubusercontent.com/11074788/87957763-fca5ca80-cab0-11ea-8cd6-9aa96f4e205c.png)

It's worth noting I'm on `#master` (wanted the `datasets` submodule).

**Comment by riedgar-ms** [comment] 2020-07-20 15:52
@torfjelde if you're on `master` did you run `pip install .` to make sure the widget was setup? I don't recall the exact reason, but I know that that's required, rather than `pip install -e .`

**Comment by torfjelde** [comment] 2020-07-20 16:42
I originally installed using `pip install git+...` but tried what you suggested just now and the same issue occurs :confused:

**Comment by romanlutz** [comment] 2020-07-20 22:57
@torfjelde what's `git+`? Are you trying to use the dashboard or change it? If you're just using it we suggest using `pip install fairlearn`. If you are trying to contribute, then please refer to the contributor guide https://fairlearn.github.io/contributor_guide/development_process.html#advanced-installation-instructions

**Comment by torfjelde** [comment] 2020-07-20 23:18
> what's git+?

Just installing from github using `pip`. But also tried by manually cloning the repo and doing `pip install .`

> Are you trying to use the dashboard or change it?

Wanted to use it, but also wanted to use the `fairlearn.datasets` submodule which wasn't available on the last release (i.e. what I get if I do `pip install fairlearn`)

**Comment by riedgar-ms** [comment] 2020-07-21 13:34
@torfjelde Does the dashboard work if you just `pip install fairlearn` rather than trying to use it directly from git? There have been some big changes in the dashboard recently, so we'd like to be sure which 'side' of them your issue is occurring.

**Comment by romanlutz** [comment] 2020-07-22 00:28
The datasets module is only available on the master branch, so either clone and install or wait for the next release. The code there is pretty minimal so you can also just copy it.

**Comment by GraemeMalcolm** [comment] 2020-08-31 22:51
I'm having the same problem in an Azure ML Compute Instance Jupyter Notebook. I created a dedicated environment as follows:

```
conda create -y -n fair python=3.6 scikit-learn pandas numpy
conda activate fair
pip install azureml-sdk[notebooks] azureml-contrib-fairness fairlearn==0.4.6
conda install -y ipykernel
ipython kernel install --user --name=aml-fair
conda deactivate
```
Restarted the kernel (and in fact restarted Jupyter on the Compute Instance), but running code to display the widget just results in the following text output:

```
<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f3442d2cc88>
```

It worked a week or so ago, and the only thing that's changed is the release of azureml-sdk 1.13 today.

**Comment by romanlutz** [comment] 2020-09-01 00:38
I'm able to repro this as well. @XuKe444 FYI

**Comment by romanlutz** [comment] 2020-09-18 19:51
Update: #578 adds Flask to do the metric calculations as opposed to ipywidgets. This should solve the issue of the dashboard not showing up on the first call after installation.

To address issues in other environments we have future work coming up. Note that this dashboard will move out of this repository & package after the next release which is why we've added a warning. More info will be in that warning and we'll point you add the package as soon as it's published.

**Comment by romanlutz** [comment] 2020-11-17 09:07
We decided to roll back the flask changes before v0.5.0 since we observed regressions in previously supported environments. Additionally, the dashboard is moving out of Fairlearn with the next release. Closing this issue similar to #639 since we won't be fixing this in this repo. For the new dashboard please refer to `raiwidgets` once it gets released at the end of the month!

**Closed by romanlutz** 2020-11-17 09:07 UTC
Labels: bug

**Comment by mjorgen1** [comment] 2021-01-12 23:35
Hi @romanlutz I am trying to use the fairness dashboard in a local jupyter notebook instance on my laptop but am having some difficulties. I installed fairlearn via pip. Here is my information: 
`
System:
    python: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable: /usr/bin/python3
   machine: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
Python dependencies:
    Cython: None
matplotlib: 3.3.3
     numpy: 1.19.0
    pandas: 1.1.5
       pip: 20.0.2
     scipy: 1.4.1
setuptools: 45.2.0
   sklearn: 0.24.0
    tempeh: None
`

When I run the below code in a cell (after following the [Fairlearn Dashboard: 2.2.1 Set-up and single model assessment](https://fairlearn.github.io/master/user_guide/assessment.html#fairlearn-dashboard) instructions),
`
from fairlearn.widget import FairlearnDashboard
FairlearnDashboard(sensitive_features=A_test, sensitive_feature_names=['race', 'gender'], y_true=y_test, y_pred=y_pred)
`

I get this as the output.
`
<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7fa16c4e5fa0>
`

Above, I see you noted that for the new dashboard we should refer to raiwidgets--How do we use raiwidgets with the fairlearn dashboard? Has the fairlearn documentation been updated with the instructions of how to use the dashboard now with raiwidgets? Please let me know. Thanks so much!

**Comment by romanlutz** [comment] 2021-01-13 02:12
Hi @mjorgen1 ! Did you try restarting the kernel? The current `FairlearnDashboard` is built on `ipywidgets` and often doesn't show up the first time because of some internals (which is one of the main reasons why we don't use that anymore in `raiwidgets`). If that still doesn't help I'd try reloading the Jupyter notebook page in your browser. 

Clearly, this kind of experience isn't ideal and a good motivation to improve things. That's why we're about to release `raiwidgets` as a separate package. There were a few delays but it's currently planned for the end of this month. By then we'll update the Fairlearn documentation as well. Currently it justs says that the `FairlearnDashboard` is deprecated and people should use `raiwidgets`, but I'll add some pointers on how to use `raiwidgets` before we release.

**Comment by xgchena** [comment] 2021-03-13 00:50
FYI: I met the same problem with Jupyter Lab, but the dashboard works for me in Jupyter Notebook.

**Comment by romanlutz** [comment] 2021-03-13 08:58
@xgchena JupyterLab is not currently supported. I would encourage you to file a feature request in the [raiwidgets package](https://github.com/microsoft/responsible-ai-widgets) for JupyterLab support, since the `FairlearnDashboard` moved to that package. The current version in Fairlearn is deprecated and will go away shortly.

**Comment by vishals2911** [comment] 2021-05-12 12:12
I am also facing this issue and read about updated and in progress task as well...could you please suggest what i need to do to see the dash board in jupyter notebook.


FairlearnWidget(value={'true_y': [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1…
<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x1f90bcb8348>



show_versions()

System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: C:\Users\vsolanki\AppData\Local\Continuum\anaconda3\python.exe
   machine: Windows-10-10.0.17134-SP0

Python dependencies:
    Cython: 0.29.14
matplotlib: 3.1.2
     numpy: 1.15.4
    pandas: 0.25.3
       pip: 19.0.3
     scipy: 1.4.1
setuptools: 51.3.3
   sklearn: 0.23.2
    tempeh: None

**Comment by mjorgen1** [comment] 2021-07-07 11:12
Hi @romanlutz I have updated my fairlearn package to 0.6.2 and I've attached a picture showing my package versions. I'm still having issues with showing the fairlearn widget when using Jupyter Notebook on my local machine, even after restarting my kernel and refreshing the notebook page as well. I've included what I'm trying to run and the output, as well as the Firefox browser console showing some issues. Thanks for your help--this functionality is really useful so I'm hoping to get this sorted.
![image](https://user-images.githubusercontent.com/29387373/124749041-acbb5000-df1b-11eb-88c8-19af34b11f18.png)
![image](https://user-images.githubusercontent.com/29387373/124749278-ee4bfb00-df1b-11eb-8d75-13816bb3bf49.png)
![image](https://user-images.githubusercontent.com/29387373/124749431-205d5d00-df1c-11eb-8c06-b69c3bc46418.png)
![image](https://user-images.githubusercontent.com/29387373/124749662-6ca89d00-df1c-11eb-9faa-37c2b10f8461.png)

**Comment by romanlutz** [comment] 2021-07-07 16:56
@mjorgen1 thanks for reaching out! If you can send me a minimal example (using the code block rendering in markdown, for example) that reproduces this issue on your machine that would be enormously helpful. Sadly, the widget is rather tricky to debug and the screenshots alone don't give me much of a hint of where things are going wrong.

Please also note that the widget has moved away from Fairlearn and is not included in the latest version v0.7.0 that was released a few hours ago. You can find (a newer version of) it in the raiwidgets package built in https://github.com/microsoft/responsible-ai-widgets if you're interested.

**Comment by mjorgen1** [comment] 2021-07-20 16:59
Hi @romanlutz, Given your advice, I updated Fairlearn and downloaded/imported raiwidgets, updated my kernel and refreshed the page, and wala! It worked. Thanks so much for your help! :)

**Comment by charlenemariscal** [comment] 2022-02-09 08:57
![image](https://user-images.githubusercontent.com/64768332/153160320-4ba86a96-01d1-4b54-a68d-96813ea103fc.png)
Hi, I want to ask that in my module, I don't have the 'widget" even though I tried to re-install the fairlearn several times

**Comment by romanlutz** [comment] 2022-02-09 23:13
@charlenemariscal which version of Fairlearn are you using? As you can see [on our website](https://fairlearn.org/v0.6.2/user_guide/assessment.html#fairlearn-dashboard) the dashboard has been removed from the `fairlearn` package. If you're using a particular version of Fairlearn (say 0.7.0) please use a notebook that was built for that version (like the one on the [corresponding release branch](https://github.com/fairlearn/fairlearn/releases) or one from the website https://fairlearn.org/v0.7.0/auto_examples/index.html).

If you want to keep using the fairness dashboard please refer to the following repo and look for "FairnessDashboard": https://github.com/microsoft/responsible-ai-toolbox

Most of the functionality can be replicated with basic plotting functions that we have in Fairlearn, though. A part of our user guide shows this: https://fairlearn.org/main/user_guide/assessment.html#plotting-grouped-metrics

I hope that helps!
