### ISSUE TITLE
simplex method failed

### ISSUE THREAD

**Issue by Bee-zest** [fairlearn/fairlearn#234] opened 2020-01-10 19:49 UTC
Sometimes I get this error. Sometimes it's fine. It seems the error is from ```/scipy/optimized/_linprog.py```

```ValueError: Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 1.7e-12 which exceeds the required tolerance of 1e-12 for a solution to be considered 'close enough' to zero to be a basic solution. Consider increasing the tolerance to be greater than 1.7e-12. If this tolerance is unacceptably  large the problem may be infeasible.```

**Comment by romanlutz** [comment] 2020-01-14 16:07
@Bee-zest thank you for raising this issue!
Can you please add 
- your fairlearn version
- whether you've made changes to fairlearn or not
- the way you're calling it
- any other context that may be useful for us to help you debug this.

Thanks!

**Comment by MiroDudik** [comment] 2020-01-27 21:08
@Bee-zest Is this repeatable on your end? Try to replace `'simplex'` with `'revised simplex'` on lines 119 and 129 of `fairlearn/reductions/_exponentiated_gradient/_lagrangian.py`. Both of the LPs are bounded and feasible, so it should also be okay to slightly increase the tolerance.

**Comment by romanlutz** [comment] 2020-01-30 15:53
I've managed to reproduce this under specific circumstances, e.g. when taking our ranking/lawschool notebook and binning by gender & race I hit this with expgrad. I'll try revised simplex as soon as I get time.

**Comment by harvineet** [comment] 2020-02-05 05:29
I found that upgrading to `scipy==1.4.1` solved this in my case. I had `scipy==1.3`. Not sure though if that is the reason. Worth a try.

**Comment by romanlutz** [comment] 2020-02-05 15:59
I'm on `scipy==1.3.1` and saw this issue as well. Will try and see whether this issue repros for me with newer versions. If so, we can bump the requirements up.

**Comment by Bee-zest** [comment] 2020-02-25 18:10
so far I increase the tolerance value. I would like to see if it can be sloved by upgrading ```scipy==1.4.1```

**Comment by romanlutz** [comment] 2020-06-15 22:35
I can confirm my previous repro doesn't work anymore, so I'll close this issue. Python 3.5 support was removed recently and `scipy<1.4.1` is a thing of the past in this repo. Please reopen if you see this issue again. Thanks!

**Closed by romanlutz** 2020-06-15 22:35 UTC
Labels: bug
