### ISSUE TITLE
cannot import name 'BoundedGroupLoss' from 'fairlearn.reductions'

### ISSUE THREAD

**Issue by anindya5** [fairlearn/fairlearn#581] opened 2020-09-21 21:26 UTC
Trying to implement BoundedGroupLoss but getting that cannot import  'BoundedGroupLoss' from 'fairlearn.reductions'.

Code was  `from  fairlearn.reductions import BoundedGroupLoss`

Fairlearn package version is latest and other fairlearn classifiers and widgets are working

**Comment by romanlutz** [comment] 2020-09-21 22:10
This sounds like a duplicate of #556 . If that's not true please reopen this issue. If it is related to #556 please just comment there. Thank you @anindya5 :-)

**Closed by romanlutz** 2020-09-21 22:10 UTC
