### ISSUE TITLE
CI bug in fetch_openml

### ISSUE THREAD

**Issue by SeanMcCarren** [fairlearn/fairlearn#1100] opened 2022-06-08 10:48 UTC
The CI checks fail on both #1079 and #947 because of errors during the calls to `fetch_openml`.

**Comment by adrinjalali** [comment] 2022-06-08 12:21
It's not a bug, the SSL certificate of openml.org is expired. A new one is requested and it should be fixed within the day.

**Closed** 2022-06-08 12:56 UTC
