### ISSUE TITLE
Widgets getting refreshed when different widgets are run

### ISSUE THREAD

**Issue by anindya5** [fairlearn/fairlearn#593] opened 2020-10-02 20:24 UTC
I initially installed fairlearn using pip install.
The fair widget was working perfectly. 

First I'd run the widget on the base model
```
from fairlearn.widget import FairlearnDashboard
FairlearnDashboard(sensitive_features=sex,
                   sensitive_feature_names=['sex'],
                   y_true=y_true,
                   y_pred={"initial model": y_pred}) 
```

Then I'd run the widget again on the mitigated model

```
from fairlearn.widget import FairlearnDashboard
FairlearnDashboard(sensitive_features=sex,
                   sensitive_feature_names=['sex'],
                   y_true=y_true,
                   y_pred={"mitigated model": y_pred_miitgated}) 
```

the default version using pip install, I was able to see two widgets one above the another and it was super helpful for comparison.

**CHANGED BEHAVIOR AFTER INSTALLING FROM GIT**
If I run the dashboard now with the mitigated output, the first dashboard also changes. Firstly, the widget does not show up in the cell below and only comes with _open in new tab_ option 

Also, the widget above that was displaying the y_pred, changes to start and while selecting them, it shows the new output. So no more comparison in the notebook.

This is not the behavior in the 0.4.6 version installed by pip

**Comment by romanlutz** [comment] 2020-10-09 18:48
@anindya5 thanks for reporting! 

I can reproduce this with the notebook "Binary Classification with the UCI Credit-card Default Dataset" which uses the dashboard in two separate cells. The second cell that executes `FairlearnDashboard` doesn't show the dashboard, only blank space, while the first cell shows what's supposed to be in the second cell output.

I'm looking into this.

**Comment by romanlutz** [comment] 2020-11-09 19:12
We had to move back to the previous version of the dashboard for v0.5.0 since the "new" version based on flask is not able to run on all the previously supported platforms yet. That will be addressed in the `raiwidgets` package which should be released by the end of the month. The dashboard will be removed from Fairlearn after the v0.5.0 release (which is planned for this week).

This mentioned rollback actually solves your problem of running multiple widgets in the same notebook, so I'm closing this issue. If you run into future issues with the dashboard from `raiwidgets` please open an issue in the corresponding repo (which will be public as soon as the release happens).

**Closed by romanlutz** 2020-11-09 19:12 UTC
Labels: bug

**Comment by anindya5** [comment] 2020-11-09 22:49
ok, where can I find details about the raiwidgets package as of now

**Comment by MarsLabAtSLU** [comment] 2020-11-10 01:31
@romanlutz and @anindya5 I have an fix for above issue without the dependency of raiwidgets. I’m working on it while I provide the fix to it. I think we still keep issue open.

**Comment by romanlutz** [comment] 2020-11-10 02:39
@anindya5 as mentioned above this package will only be released at the end of the month. The rolled back version of the `FairlearnDashboard` does not show the same issue you described.

@MarsLabAtSLU I commented on your new issue #629 . The fix won't be needed in this repo since the widget is moving out of the repo, but feel free to share if you already have a branch and we can adopt that approach for `raiwidgets`.
