### ISSUE TITLE
Mitigation with Fairlearn for Regression

### ISSUE THREAD

**Issue by MG-Microsoft** [fairlearn/fairlearn#897] opened 2021-07-14 02:34 UTC
#### Is your feature request related to a problem? Please describe.
I have trained a regression model for predicting wait time in hospitals and would love to showcase it as ademo for MST customers that how fairlearn can help to mitigate for this regression model while there is no regression support for mitigation in Fairlearn now!

#### Describe the solution you'd like
Desigin a similar module that we have for classification, now this time for regression to mitigate it using GridSearch or something similar.

#### Describe alternatives you've considered, if relevant
There is no alternative

**Comment by hildeweerts** [comment] 2021-07-14 08:30
Hi @MG-Microsoft. Our `reductions` module offers support for regression tasks. You can find more information in our [user guide](https://fairlearn.org/v0.6.2/user_guide/mitigation.html#fairness-constraints-for-regression).

Please let me know if this answers your question.

**Comment by MG-Microsoft** [comment] 2021-07-14 11:56
Thank you so much for your reply!
If I understood properly, this reduction method for regression is a post-processing method while in classification (using GridSearch), we can mitigate within the training process. So, we do not support a similar thing in regression? That was my feature request.
Also in bounded group loss example of your link, we have  :
bgl = BoundedGroupLoss(ZeroOneLoss(), upper_bound=0.1)

ZeroOneLoss is defining the min_val to be 0 and max_val to be 1. Then the question is what is upper bound ?

Regards,
Mohammad

**Comment by riedgar-ms** [comment] 2021-07-14 12:09
Sorry, we must have miscommunicated in our call. The `reductions` methods always work by retraining the models in various ways.

**Comment by hildeweerts** [comment] 2021-07-14 12:27
Hi, @MG-Microsoft.

> If I understood properly, this reduction method for regression is a post-processing method while in classification (using GridSearch), we can mitigate within the training process. So, we do not support a similar thing in regression? That was my feature request.

The reductions approach does not work as a post-processing algorithm for an existing machine learning model but more like a 'wrapper' over a learning algorithm.
An example of how we can use `GridSearch` can be found [here](https://fairlearn.org/v0.7.0/auto_examples/plot_grid_search_census.html#mitigation-with-gridsearch). In the regression scenario, you can replace the `DemographicParity` constraint with `BoundedGroupLoss` (please correct me if I'm wrong about this @MiroDudik @romanlutz @riedgar-ms).


> Also in bounded group loss example of your link, we have  :
bgl = BoundedGroupLoss(ZeroOneLoss(), upper_bound=0.1)

I think the Note below the example answers your question regarding the upperbound: *"In the example above the BoundedGroupLoss object does not use the upper_bound argument. It is only used by reductions techniques during the unfairness mitigation. As a result the constraint violation detected by gamma is identical to the mean absolute error."*

**Comment by romanlutz** [comment] 2021-07-14 17:09
From a technical standpoint your answer is absolutely correct @hildeweerts. As mentioned elsewhere we always advocate for being mindful of your application context. `BoundedGroupLoss` is the only regression constraint we currently support, but that doesn't necessarily mean that it's appropriate for your context. 

I will close this issue since it's a misunderstanding/question that's been answered, but I think we need to redouble our efforts on documenting reductions.

**Closed by romanlutz** 2021-07-14 17:09 UTC
