### ISSUE TITLE
Matplotlib deprecation messages when running Example Notebook code

### ISSUE THREAD

**Issue by RWilsker** [fairlearn/fairlearn#937] opened 2021-08-13 02:28 UTC
When I run the MetricFrame Visualization code sample (plot_quickstart.ipynb), I get the following error messages:

`C:\Users\xxxxxxx\Anaconda3\envs\fairlearn_env\lib\site-packages\pandas\plotting\_matplotlib\tools.py:331: MatplotlibDeprecationWarning: 
The is_first_col function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use ax.get_subplotspec().is_first_col() instead.
  if ax.is_first_col():
C:\Users\xxxxxxx\Anaconda3\envs\fairlearn_env\lib\site-packages\pandas\plotting\_matplotlib\tools.py:331: MatplotlibDeprecationWarning: 
The is_first_col function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use ax.get_subplotspec().is_first_col() instead.
  if ax.is_first_col():
C:\Users\xxxxxxx\Anaconda3\envs\fairlearn_env\lib\site-packages\pandas\plotting\_matplotlib\core.py:1547: MatplotlibDeprecationWarning: normalize=None does not normalize if the sum is less than 1 but this behavior is deprecated since 3.3 until two minor releases later. After the deprecation period the default value will be normalize=True. To prevent normalization pass normalize=False 
  results = ax.pie(y, labels=blabels, **kwds)`

This behavior persisted after I did a 'conda update matplotlib' to ensure I was using the latest version.

**Comment by riedgar-ms** [comment] 2021-08-13 13:35
Thanks for highlighting this.

Looking at the example code (e.g. [here](https://github.com/fairlearn/fairlearn/blob/c51e619e903a4652c79c02e375f145091408a5f3/examples/plot_quickstart.py#L54)), this isn't our plotting code per se - the `by_group` property is a `DataFrame`, so we're just delegating to `pandas` plotting routines.

Can you check which version of `pandas` you're using?

**Comment by romanlutz** [comment] 2021-08-14 23:04
This was also previously mentioned in #852 as a warning that shows up in our builds.

**Comment by romanlutz** [comment] 2021-12-15 03:11
FWIW I can't reproduce this on my machine with the following versions:
```
System:
    python: 3.8.5 
   machine: macOS

Python dependencies:
    Cython: None
matplotlib: 3.4.3
     numpy: 1.19.5
    pandas: 1.3.4
       pip: 20.1.1
     scipy: 1.7.1
setuptools: 49.2.0
   sklearn: 1.0.1
```

Since we don't have version numbers from the original post I'm going to close the issue. @RWilsker feel free to reopen if you can post your versions (using `fairlearn`'s `show_versions()`). I suspect `pandas` is seeing those warnings in the corresponding version and hopefully fixed them along the way, so an upgrade to the latest version of pandas should do the trick. Without knowing your exact versions it's hard to confirm, though.

@alliesaizan the `plot_quickstart.py` file is under `examples`, but `sphinx-gallery` builds this into the documentation we see on the website, so it ends up in the build directory under `docs` even though the source file doesn't live there.

**Closed by romanlutz** 2021-12-15 03:11 UTC
Labels: documentation
